package com.sas.spock;
import org.safs.model.Component;
import org.safs.model.tools.RuntimeDataAware;
import org.safs.tools.RuntimeDataInterface;

/** *** DO NOT EDIT THIS FILE ***<br>
    THIS FILE IS GENERATED AUTOMATICALLY by org.safs.model.tools.ComponentGenerator!<br><p>
    A JSAFS AppMap reference for SAFS App Map: 'C:/SePlusProjects/Spock/Maps' */
public final class Map implements RuntimeDataAware {

    private static RuntimeDataInterface dataInterface = null;

    /** Called internally as part of the bootstrap process of Dependency Injection. */
    public void setRuntimeDataInterface(RuntimeDataInterface helper){
        dataInterface = helper;
    }

    // The Names of ApplicationConstants:

    /** "GoogleBrowser" */
    public static final String GoogleBrowser = "GoogleBrowser";

    /** The resolved runtime value of constant 'GoogleBrowser', or null. */
    public static String GoogleBrowser(){
        try{ return dataInterface.getVariable("GoogleBrowser"); }
        catch(Exception x){ return null; }
    }

    /** "GoogleURL" */
    public static final String GoogleURL = "GoogleURL";

    /** The resolved runtime value of constant 'GoogleURL', or null. */
    public static String GoogleURL(){
        try{ return dataInterface.getVariable("GoogleURL"); }
        catch(Exception x){ return null; }
    }

    // The Names of Window and Child Component objects: 

    /** "GoogleHome" Component and its children. */
    public static class GoogleHome {

        // No use for a default constructor.
        private GoogleHome(){}

        /** "GoogleHome" Window Component itself. */
        public static final Component GoogleHome = new Component("GoogleHome");

        /** "SignInButton" Component in "GoogleHome". */
        public static final Component SignInButton = new Component(GoogleHome, "SignInButton");
    }

    /** "GoogleLogin" Component and its children. */
    public static class GoogleLogin {

        // No use for a default constructor.
        private GoogleLogin(){}

        /** "GoogleLogin" Window Component itself. */
        public static final Component GoogleLogin = new Component("GoogleLogin");

        /** "EmailText" Component in "GoogleLogin". */
        public static final Component EmailText = new Component(GoogleLogin, "EmailText");
    }

    /** "ApplicationConstants" Component and its children. */
    public static class ApplicationConstants {

        // No use for a default constructor.
        private ApplicationConstants(){}

        /** "ApplicationConstants" Window Component itself. */
        public static final Component ApplicationConstants = new Component("ApplicationConstants");

        /** "GoogleBrowser" Component in "ApplicationConstants". */
        public static final Component GoogleBrowser = new Component(ApplicationConstants, "GoogleBrowser");

        /** "GoogleURL" Component in "ApplicationConstants". */
        public static final Component GoogleURL = new Component(ApplicationConstants, "GoogleURL");
    }
}
